JDBCurl : jdbc:mysql://localhost:3306/Java_CADS?&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
userName : root
passWord : ## put your database password here
userTable : user_list
rocketTable :
